name=ModeloEdgeImpulse
version=1.0.0
author=Projeto Inimigo da Linha
maintainer=Projeto Inimigo da Linha
sentence=Inferencia Edge Impulse e conversao de saidas para PWM.
category=Signal Input/Output
architectures=esp32
