name=ColetaDados
version=1.0.0
author=Projeto Inimigo da Linha
maintainer=Projeto Inimigo da Linha
sentence=Coleta de sensores e comandos de motores em buffer RAM e LittleFS.
category=Data Processing
architectures=esp32
